const express = require('express');
const router = express.Router();
const cartController = require('../controllers/cartcontroller');
const { authMiddleware } = require("../middleware/authMiddleware");
router.post('/addtocart', authMiddleware, cartController.addToCart);
router.get('/viewcart', authMiddleware, cartController.viewCart);
router.put('/removefromcart', authMiddleware, cartController.removeFromCart);
router.put('/updatecart/:productId', authMiddleware, cartController.updateCartQuantity);
router.put('/updateproductq/:productId', authMiddleware, cartController.updateProductQuantity);
router.post('/addtowishlist', authMiddleware, cartController.addToWishlist);
router.get('/viewwishlist', authMiddleware, cartController.viewWishlist);
router.delete('/removefromwishlist', authMiddleware, cartController.removeFromWishlist);
router.post('/checkout',authMiddleware, cartController.checkout);
router.get('/orders/history/:orderId',authMiddleware, cartController.viewOrderHistory);
router.get('/orders/history',authMiddleware, cartController.OrderHistory);
router.post('/orders/confirm-payment',authMiddleware, cartController. confirmPayment);
router.delete('/orders/cancel', authMiddleware,cartController. cancelOrder);
router.post('/fetchorderdetail', authMiddleware, cartController.FetchOrderDetail);
module.exports = router;